export default {
    ALERT_SUCCESS: "Your message was sent successfully!",
    LOADING: "Loading...",
    PREVIOUS_PAGE: "Previous Page",
    NEXT_PAGE: "Next Page",
    DEVICE_ID: "Device ID",
    DISPLAY_NAME: "Display Name",
    ACTIVE_STATE: "Active State",
    ONLINE: "Online",
    LATITUDE: "Latitude",
    LONGITUDE: "Longitude",
    ALTITUDE: "Altitude",
    DRIVE_STATUS: "Drive Status",
    ICON: "Icon",
    PREFERENCES: "Preferences",
    SORT_COLUMN: "Sort Column",
    SORT_ORDER: "Sort Order",
    ASCENDING: "Ascending",
    DESCENDING: "Descending",
    NUMBER_OF_ROWS: "Number of Rows",
    EDIT_DEVICE_PREFERENCES: "Edit Device Preferences",
    HIDDEN: "Hidden",
    EDIT: "Edit",
    SAVE: "Save",
    SEARCH: "Search...",
}